### ISSUE TITLE
Getting an error 'TypeError: betterSqlite3StoreFactory is not a function'

### ISSUE THREAD

**Issue by isriram** [porridgewithraisins/ts-better-sqlite3-express-session#1]
```
import expressSession from "express-session";
import sqlite from "better-sqlite3";
import betterSqlite3StoreFactory from "ts-better-sqlite3-express-session";

const sessionsDB = new sqlite("./sessions.db");
const sqliteStore = betterSqlite3StoreFactory(expressSession);
```

The above code gives me an error "TypeError: betterSqlite3StoreFactory is not a function".
I am not sure what I'm doing wrong.

**Comment by porridgewithraisins** [comment]
Hi!
So I managed to reproduce your issue by using this package from JavaScript.

The example code given in the README works for TypeScript (it could be generating either ESM or CommonJS, doesn't matter).
However,
In commonJS Javascript, you have to import it like
```js
const { default: betterSqlite3StoreFactory } = require("ts-better-sqlite3-express-session");
```
and in ESM JavaScript, you have to import it like
```js
import betterSqlite3StoreFactory_ from "ts-better-sqlite3-express-session";
const betterSqlite3StoreFactory = betterSqlite3StoreFactory_.default;
```

I will add these to the README for now, and then see if it is possible to change my `tsconfig.json` so it emits code that is easier to import.
